### ISSUE TITLE
Local state use

### ISSUE THREAD

**Issue by AlfGNC** [JossDuff/reach-crowdfund#1]
"This Reach application is dangerous to run on Algorand for the following reasons:
 * This program was compiled with trustworthy maps, but maps are not trustworthy on Algorand, because they are represented with local state. A user can delete their local state at any time, by sending a ClearState transaction. The only way to use local state properly on Algorand is to ensure that a user doing this can only 'hurt' themselves and not the entire system."

I tried to run the script and this shows up. I cannot find hints on how to solve this on reach language page and in the examples in the websites. I understood what it wants, but not how to solve.

P.S. Thank you for this great work 
![cf_log](https://user-images.githubusercontent.com/74142883/171616027-672dce5a-d52a-45bc-9c0c-1950d66384a9.png)

**Comment by JossDuff** [comment]
Hi!  Thanks for bringing this up, I'm going to add a comment about it in the readme because everyone will run into this and undoubtedly have questions.

This is a Reach warning that gets printed every time your code accesses a mapping while running your Reach program in Algorand mode.  To 'fix' this issue, you need to ensure that there is no incentive for an individual to clear their local state.  In this program, mappings are being used to track who has donated to a fund and how much they have donated.  These mapping are used later to allow users to reclaim their donations in the event that a fund did not meet its goal.  If a user cleared their mappings (by deleting their local state), the only thing that happens is that they lose the ability to reclaim their own donations if the fund doesn't meet its goal.  This only 'hurts' the person clearing their state, and not the entire system.

There is currently no way to suppress this message in Algorand mode because its a security concern.  However, this message won't be printed if your run your program in Ethereum mode because mappings aren't represented with local state on Ethereum.  Reach is very convenient because you can easily run this program in Ethereum without having to make any changes to your code.

To switch to Ethereum and avoid this message, run the following command in your terminal in the same folder as your 'reach' executable:
`REACH_CONNECTOR_MODE=ETH`
This tells Reach to compile as an Ethereum program and now you should be able to re-run without that warning.

To check what connector mode you are in, you can run
`echo $REACH_CONNECTOR_MODE`

Hope this helps :)

**Comment by AlfGNC** [comment]
Oh perfect, it makes sense! I had also noticed that running in the ethereum network it worked fine. 
Thanks again for the answer and for the great work, it is really helpful!
